logging:
  level:
    net:
      ttddyy:
        dsproxy:
          listener: debug
    ru:
      dinerik:
        ECM: info
    org:
      hibernate:
        type: error
    root: error
spring:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5433/ECMdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#    show-sql:
#      true
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always